name: Docker Image CI for main branch

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build --platform linux --tag jos3f19/dev_ops:latest -f Dockerfile .
      - name: Publish Docker Image
        run: |
          docker push jos3f19/dev_ops:latest
          
